DROP DATABASE IF EXISTS todo;
CREATE DATABASE IF NOT EXISTS todo;
USE todo;

CREATE TABLE IF NOT EXISTS list(
    id int AUTO_INCREMENT, 
    items VARCHAR(200),
    chek BOOLEAN ,
    PRIMARY KEY (id)
);